apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-deployment
  labels:
    app: node-web-app
spec:
  replicas: 3
  template:
    metadata:
      name: node-web-app
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: vishaldwivedi13/node-web-app:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: node-web-app